# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c8jirzgrz-capi-aws
  namespace: c8jirzgrz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: c8jirzgrz-capi-aws
subjects:
- kind: ServiceAccount
  name: c8jirzgrz-capi-aws
